### PR TITLE
Update dockerfile-qt

### PR DESCRIPTION
**Pull request by stevenkordonowy**
Add python package installs for 'networkx' and 'noisyopt'

### CODE REVIEW

**Comment by dirkcgrunwald** [comment]
I'm assuming you want the container rebuilt - I will do that right now.

**Comment by stevenkordonowy** [comment]
@dirkcgrunwald that would be great, thanks! In general, is this how you would prefer we make changes?

**Comment by dirkcgrunwald** [comment]
Yup

**Comment by dirkcgrunwald** [comment]
I restarted jupyter hub & checked that *pip list | grep -i noise* shows the
new package. Looks like you're good to go.

**Pull request merged**
